version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clean-architecture-sample-app
    volumes:
      - .:/usr/local/app
    working_dir: /usr/local/app
    ports:
      - "8000:8000"
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "pnpm install && pnpm prisma generate && pnpm prisma db push && pnpm dev",
      ]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.1.0
    platform: linux/x86_64
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clean-architecture-sample-app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: "5s"
      interval: "30s"
    volumes:
      - clean-architecture-sample-app-data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d
volumes:
  clean-architecture-sample-app-data:
